version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileFrontendAAL
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Activa polling para asegurar detección de cambios en Docker
    networks:
      - redwebAAL
    container_name: frontendAAL

  backend:
    build:
      context: ./backend
      dockerfile: DockerfileBackendAAL
    command: bash -c "composer install && php -S 0.0.0.0:8000 -t public"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - redwebAAL
    container_name: backendAAL

  web:
    build:
      context: ./web
      dockerfile: DockerfileWebAAL
    ports:
      - "80:80" # Si tienes problemas con el puerto 80, cambia el puerto externo aquí
    networks:
      - redwebAAL
    container_name: webAAL 

networks:
  redwebAAL:
    driver: bridge
